easy_admin:
    site_name: 'Administration'
    design:
        menu:
            - { entity: 'User', default: true }
            - { entity: 'Category' }
            - { entity: 'JobOffer' }
            - { entity: 'City' }
            - { entity: 'District' }
            - { label: 'Statistiques', route: 'stats' }
            - { label: 'Retour vers le site',  route: 'index' }
    formats:
        datetime: 'd F Y - H:i'
    list:
        actions:
            - { name: 'show', icon: 'info', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'times', label: '' }
    edit:
        actions: [ '-delete' ]
    show:
        actions: [ '-delete', '-edit' ]
    entities:
        Category:
            class: App\Entity\Category
            label: Catégories
            list:
                title: Liste des catégories
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'description', label: 'Description' }
                sort: ['title', 'ASC']
                actions:
                    - { name: 'new', label: 'Ajouter une catégorie' }
            show:
                fields:
                - { property: 'title', label: 'Titre' }
                - { property: 'description', label: 'Description' }
            edit:
                title: 'Modifier la catégorie'
            new:
                title: 'Ajouter une nouvelle catégorie'
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'description', label: 'Description' }
            search:
                fields: ['title']
        User:
            class: App\Entity\User
            label: Utilisateurs
            list:
                title: Liste des utilisateurs
                sort: ['username', 'ASC']
                fields:
                    - { property: 'username', label: 'Compte' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'registrationDate', label: 'Inscrit depuis le' }
                    - { property: 'isActive', label: 'Compte activé', type: 'boolean' }
            show:
                fields:
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Adresse email' }
                    - { property: 'firstName', label: 'Prénom' }
                    - { property: 'lastName', label: 'Nom' }
                    - { property: 'birthdate', label: 'Date de naissance' }
                    - { property: 'phoneN1', label: 'Téléphone privé' }
                    - { property: 'phoneN2', label: 'Téléphone mobile' }
                    - { property: 'address', label: 'Adresse' }
                    - { property: 'city', label: 'Localité' }
            disabled_actions:
                - 'new'
                - 'edit'
        JobOffer:
            class: App\Entity\JobOffer
            label: Offres
            list:
                title: Liste des offres
                help: 'Seul les offres en cours de publication sont affichées'
                dql_filter: 'entity.isActive = true'
                fields:
                    - { property: 'title', label: "Titre de l'annonce" }
                    - { property: 'description', label: 'Description' }
                    - { property: 'city', label: 'Lieu' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'offerType', label: 'Type' }
                    - { property: 'publicationDate', label: 'Date de publication' }
                sort: ['publicationDate', 'DESC']
                actions:
                    -
                        name: 'closeOffer'
                        icon: 'times'
                        label: ''
            show:
                fields:
                    - { property: 'title', label: "Titre de l'annonce" }
                    - { property: 'description', label: 'Description' }
                    - { property: 'city', label: 'Lieu' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'offerType', label: 'Type' }
                    - { property: 'publicationDate', label: 'Date de publication' }
                    - { property: 'user', label: 'Utilisateur' }
            disabled_actions:
                - 'new'
                - 'edit'
                - 'delete'
            search:
                fields: ['title', 'city', 'offerType' ]
        City:
            class: App\Entity\City
            label: Localités
            list:
                title: Liste des localités
                fields:
                    - { property: 'npa', label: 'NPA', type: 'string' }
                    - { property: 'name', label: 'Localité' }
                    - { property: 'district', label: 'District' }
                sort: ['npa', 'ASC']
                actions:
                    - { name: 'new', label: 'Ajouter une localité' }
            edit:
                title: 'Modifier la localité'
            new:
                title: 'Ajouter une localité'
            form:
                fields:
                    - { property: 'npa', label: 'NPA' }
                    - { property: 'name', label: 'Localité' }
                    - { property: 'district', label: 'District' }
        District:
            class: App\Entity\District
            label: District
            list:
                title: Liste des districts
                fields:
                    - { property: 'name', label: 'Nom' }
                sort: ['name', 'ASC']
                actions:
                    - { name: 'new', label: 'Ajouter un district' }
            new:
                title: 'Ajouter un district'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'canton', label: 'Canton' }
            edit:
                title: 'Modifier le district'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'canton', label: 'Canton' }
            show:
                fields:
                - { property: 'name', label: 'Nom' }
                - { property: 'canton', label: 'Canton' }
