security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_provider]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$00ps6qsY6vnUpAYD8kajv.fEgsyS67jrjDhs1qhseUk8yYP13RnU6
                        roles: 'ROLE_ADMIN'
        user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/
            http_basic: true
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: username
                password_parameter: password
            logout:
                path: /logout
                target: /
        admin:
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: username
                password_parameter: password
                default_target_path: /admin
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/ajouter-une-annonce, roles: ROLE_USER }
        - { path: ^/gerer-mes-annonces, roles: ROLE_USER }
        - { path: ^/mon-compte, roles: ROLE_USER }
