security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        #in_memory: { memory: ~ }
        user_provider:
            entity:
              class: App\Entity\User
              property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/
            http_basic: true
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/ajouter-une-annonce, roles: ROLE_USER }
        - { path: ^/gerer-mes-annonces, roles: ROLE_USER }
        - { path: ^/mon-compte, roles: ROLE_USER }
