vich_uploader:
    db_driver: orm

    mappings:
        profile_image:
            uri_prefix: /profile_images
            upload_destination: '%kernel.project_dir%%path_upload_images%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'id' }

        user_document:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%%path_upload_documents%'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'user.id' }
            namer:
                service: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_remove: false