vich_uploader:
    db_driver: orm

    mappings:
        image_profile:
            uri_prefix: /public/build/profile_images
            upload_destination: '%kernel.project_dir%/public/build/profile_images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
