<?php
namespace App\Controller;

use App\Entity\Closing;
use App\Entity\ClosingType;
use App\Entity\JobOffer;
use App\Entity\User;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController as BaseAdminController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class AdminController extends BaseAdminController
{
    private $mailer;

    public function __construct(\Swift_Mailer $mailer)
    {
        $this->mailer = $mailer;
    }

    /**
     * @Route("/admin", name="admin")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function indexAction(Request $request)
    {
        return parent::indexAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @Route("/admin/statistiques", name="stats")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function stats()
    {
        return $this->render('easy_admin/stats.html.twig');
    }

    /**
     * Description : Quand l'administrateur supprime une annonce, cela ne la supprime pas pour de bon mais cela la ferme, histoire de garder un historique
     * avant une éventuelle suppression du compte
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function closeOfferAction()
    {
        $closing = new Closing();

        $jobOffer = $this->em->getRepository(JobOffer::class)->findOneBy(array(
            'id' => $this->request->query->get('id')
        ));

        $closingType = $this->em->getRepository(ClosingType::class)->findOneBy(array(
            'name' => 'admin'
        ));

        $user = $this->em->getRepository(User::class)->findOneBy(array(
            'id' => $jobOffer->getUser()->getId()
        ));

        $this->em->persist($closing);

        $closing->setClosingType($closingType);
        $closing->setDate(new \DateTime());

        $jobOffer->setClosing($closing);
        $jobOffer->setIsActive(false);

        $this->em->flush();

        $this->addFlash('success', 'L\'annonce a bien été supprimée');

        $email = (new \Swift_Message('Suppresion d\'une annonce'))
            ->setSubject('Bourse Emploi - Caritas Jura')
            ->setFrom($this->getParameter('email'))
            ->setTo($user->getEmail())
            ->setBody(
                $this->renderView(
                    'emails/emailOfferDeleted.html.twig',
                    array(
                        'userFirstName' => $user->getFirstName(),
                        'offerTitle' => $jobOffer->getTitle(),
                        'offerPublicationDate' => $jobOffer->getPublicationDate(),
                        'email' => $this->getParameter('email')
                    )
                ),
                'text/html'
            );

        $this->mailer->send($email);

        return $this->redirectToRoute('admin', array(
            'action' => 'list',
            'entity' => $this->request->query->get('entity')
        ));
    }
}
