logout:
    path: /logout

index:
    path: /
    controller: App\Controller\AppController::index

easyadmin:
    path: /admin

searchJob:
    path: /recherche-emploi
    controller: App\Controller\AppController::listSearchJob

searchOffers:
    path: /offre-emploi
    controller: App\Controller\AppController::listOfferJob

infoChequeEmploi:
    path: /cheque-emploi
    controller: App\Controller\AppController::viewChequeEmploi

conditions:
    path: /conditions-generales-utilisation
    controller: App\Controller\AppController::viewConditions

filter:
    path: /filtrer
    controller: App\Controller\AppController::filterList